### ISSUE TITLE
Flickr pages

### ISSUE THREAD

**Issue by pgogy** [nyergler/openattribute-firefox#20]
Hey,

Tried to use the latest version from here

http://www.flickr.com/photos/chigle/5185078229/

this pages fails when logged in and when logged out?

Not sure what this means?

**Comment by nyergler** [comment]
Works fine for me. Were you using 0.9.2 (released yesterday)? 0.9 had a bug that prevented pages from being re-parsed when they changed. So if you started your browser session logged into Flickr, visited the page and did not see a license (which is the correct behavior given their screwy templates), then logged out, you still would not see the license show up. This should be fixed in the latest release. Can you confirm you're using that?

**Comment by pgogy** [comment]
That is almost certainly it - it seemed almost surreal how it worked then didn't.
I took the version down from here into my local copy? Should I just install the add on and then take the code out of it?

**Comment by nyergler** [comment]
I don't understand what you mean by this question :). You can get the latest code (that I think should) from either git (here), or from AMO (https://addons.mozilla.org/en-US/firefox/addon/openattribute/).

**Comment by pgogy** [comment]
Ok, if its the same thing then maybe I did wrong. I'll make a new profile and test. Thanks.

**Comment by pgogy** [comment]
Problem between computer and keyboard. Now solved.
