### ISSUE TITLE
Not finding author information in content attribute of spans

### ISSUE THREAD

**Issue by greggrossmeier** [nyergler/openattribute-firefox#30]
From a coworker: 

I notice that the OpenAttribute plugin for Firefox 4.+ (0.9.6) and Chrome (0.6) can't identify the author if set as the 'content' attribute of a span but can if it's the content of the span element. It's nice to put values in an attribute of an empty span to avoid having to hide the display of the span content with CSS. Or would it be considered incorrect to use the 'content' attribute for this purpose?

``` html
 <span property="cc:attributionName" rel="cc:attributionURL" href="http://hdl.handle.net/2027/mdp.39015003435131" content="Nowick, Arthur S."></span>
```

**Comment by nyergler** [comment]
Definitely an issue; is there an example in the wild I can use for testing?

**Comment by ghost** [comment]
Here's an example from the HathiTrust pageturner at: http://hdl.handle.net/2027/mdp.39015015823563

It contains this span:

<span property="cc:attributionName" rel="cc:attributionURL" href="http://hdl.handle.net/2027/mdp.39015015823563" content="Brooklyn Museum."></span>

Regards,
Phil

**Comment by nyergler** [comment]
This is actually a problem with the Hathi Trust markup. By nesting the licensing assertion in the link to "http://www.hathitrust.org/access_use#cc-by-nc", the license assertion becomes "relative" to that URL. That is, the RDFa at http://babel.hathitrust.org/cgi/pt?id=mdp.39015015823563 says that http://www.hathitrust.org/access_use#cc-by-nc is licensed under CC BY-NC. Because the attribution markup _is_ correct, it refers to the actual page URL as the subject. The mismatch causes the following to be generated as the attribution HTML (note the presence of the access_use#cc-by-nc URL as the work URL, which is the tip off):

<code>&lt;span about="http://www.hathitrust.org/access_use#cc-by-nc">Work found at &lt;a href="http://www.hathitrust.org/access_use#cc-by-nc">http://www.hathitrust.org/access_use#cc-by-nc&lt;/a>  / &lt;a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/us/">CC BY-NC 3.0&lt;/a>&lt;/span>
</code>

Apologies for taking so long to triage this. Closing the issue now because it looks like it's a markup issue, not an issue with the extension. Feel free to contact me if you need assistance updating or validating the markup.
